spring.application.name=finsight

spring.dotenv.filename=.env.${spring.profiles.active:.local}

# ===============================
# DATABASE CONFIG
# ===============================
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.globally_quoted_identifiers=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB


server.http2.enabled=true
server.port=${SERVER_PORT:3000}

# ===============================
# JWT CONFIG
# ===============================
jwt.secret-key=${JWT_SECRET_KEY}
jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}

# ===============================
# DOCS
# ===============================
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.operations-sorter=alpha
