--
-- Flyway baseline (V1) — generated from the live dev schema via `pg_dump --schema-only`.
-- On the existing dev DB this is NOT executed (baseline-on-migrate marks it applied);
-- on a fresh/empty DB (e.g. prod) it runs to build the starting schema.
-- psql meta-commands (\restrict/\unrestrict) and the empty search_path were removed
-- so the file is pure SQL runnable by Flyway.
--

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: financial_transaction_categories; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.financial_transaction_categories (
    id bigint NOT NULL,
    description character varying(255),
    spending_limit numeric(38,2),
    user_id bigint NOT NULL,
    type character varying(255),
    CONSTRAINT financial_transaction_categories_type_check CHECK (((type)::text = ANY ((ARRAY['CREDIT'::character varying, 'DEBIT'::character varying])::text[])))
);


--
-- Name: financial_transaction_categories_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.financial_transaction_categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.financial_transaction_categories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: financial_transactions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.financial_transactions (
    id bigint NOT NULL,
    amount numeric(38,2),
    description character varying(255),
    end_date date,
    frequency character varying(255),
    parcels_number integer,
    start_date date,
    type character varying(255),
    category_id bigint,
    user_id bigint NOT NULL,
    external_id character varying(255),
    series_id character varying(255),
    CONSTRAINT financial_transactions_type_check CHECK (((type)::text = ANY ((ARRAY['CREDIT'::character varying, 'DEBIT'::character varying])::text[])))
);


--
-- Name: financial_transactions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.financial_transactions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.financial_transactions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    email character varying(255),
    name character varying(255),
    password character varying(255)
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: financial_transaction_categories financial_transaction_categories_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.financial_transaction_categories
    ADD CONSTRAINT financial_transaction_categories_pkey PRIMARY KEY (id);


--
-- Name: financial_transactions financial_transactions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.financial_transactions
    ADD CONSTRAINT financial_transactions_pkey PRIMARY KEY (id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: idx_financial_transactions_start_date; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_financial_transactions_start_date ON public.financial_transactions USING btree (start_date);


--
-- Name: idx_financial_transactions_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_financial_transactions_user_id ON public.financial_transactions USING btree (user_id);


--
-- Name: idx_financial_transactions_user_id_series_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_financial_transactions_user_id_series_id ON public.financial_transactions USING btree (user_id, series_id);


--
-- Name: idx_financial_transactions_user_id_start_date; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_financial_transactions_user_id_start_date ON public.financial_transactions USING btree (user_id, start_date);


--
-- Name: financial_transaction_categories fk_financial_transaction_categories_users; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.financial_transaction_categories
    ADD CONSTRAINT fk_financial_transaction_categories_users FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: financial_transactions fk_financial_transactions_financial_transaction_categories; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.financial_transactions
    ADD CONSTRAINT fk_financial_transactions_financial_transaction_categories FOREIGN KEY (category_id) REFERENCES public.financial_transaction_categories(id);


--
-- Name: financial_transactions fk_financial_transactions_users; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.financial_transactions
    ADD CONSTRAINT fk_financial_transactions_users FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- PostgreSQL database dump complete
--

