--
-- Shared Plans (V2) — creates the plan domain tables: plans, plan_memberships, plan_invitations.
-- Mirrors the column-type conventions of V1 (bigint IDENTITY PKs, character varying(255)
-- for strings/enums, enum columns as varchar with CHECK constraints). Pure SQL only.
--

--
-- Name: plans; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.plans (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    created_by bigint NOT NULL,
    is_default boolean NOT NULL
);


ALTER TABLE public.plans ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.plans_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: plan_memberships; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.plan_memberships (
    id bigint NOT NULL,
    plan_id bigint NOT NULL,
    user_id bigint NOT NULL,
    role character varying(255) NOT NULL,
    CONSTRAINT plan_memberships_role_check CHECK (((role)::text = ANY ((ARRAY['OWNER'::character varying, 'EDITOR'::character varying, 'CONTRIBUTOR'::character varying, 'VIEWER'::character varying])::text[])))
);


ALTER TABLE public.plan_memberships ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.plan_memberships_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: plan_invitations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.plan_invitations (
    id bigint NOT NULL,
    plan_id bigint NOT NULL,
    role character varying(255) NOT NULL,
    type character varying(255) NOT NULL,
    email character varying(255),
    token character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    invited_by bigint NOT NULL,
    expires_at timestamp(6) without time zone,
    CONSTRAINT plan_invitations_role_check CHECK (((role)::text = ANY ((ARRAY['OWNER'::character varying, 'EDITOR'::character varying, 'CONTRIBUTOR'::character varying, 'VIEWER'::character varying])::text[]))),
    CONSTRAINT plan_invitations_type_check CHECK (((type)::text = ANY ((ARRAY['EMAIL'::character varying, 'LINK'::character varying])::text[]))),
    CONSTRAINT plan_invitations_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'ACCEPTED'::character varying, 'REVOKED'::character varying])::text[])))
);


ALTER TABLE public.plan_invitations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.plan_invitations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Primary keys
--

ALTER TABLE ONLY public.plans
    ADD CONSTRAINT plans_pkey PRIMARY KEY (id);


ALTER TABLE ONLY public.plan_memberships
    ADD CONSTRAINT plan_memberships_pkey PRIMARY KEY (id);


ALTER TABLE ONLY public.plan_invitations
    ADD CONSTRAINT plan_invitations_pkey PRIMARY KEY (id);


--
-- Unique constraints
--

ALTER TABLE ONLY public.plan_memberships
    ADD CONSTRAINT uk_plan_memberships_plan_user UNIQUE (plan_id, user_id);


ALTER TABLE ONLY public.plan_invitations
    ADD CONSTRAINT uk_plan_invitations_token UNIQUE (token);


--
-- Foreign keys
--

ALTER TABLE ONLY public.plans
    ADD CONSTRAINT fk_plans_created_by FOREIGN KEY (created_by) REFERENCES public.users(id);


ALTER TABLE ONLY public.plan_memberships
    ADD CONSTRAINT fk_plan_memberships_plan FOREIGN KEY (plan_id) REFERENCES public.plans(id);


ALTER TABLE ONLY public.plan_memberships
    ADD CONSTRAINT fk_plan_memberships_user FOREIGN KEY (user_id) REFERENCES public.users(id);


ALTER TABLE ONLY public.plan_invitations
    ADD CONSTRAINT fk_plan_invitations_plan FOREIGN KEY (plan_id) REFERENCES public.plans(id);


ALTER TABLE ONLY public.plan_invitations
    ADD CONSTRAINT fk_plan_invitations_invited_by FOREIGN KEY (invited_by) REFERENCES public.users(id);
