--
-- Expense Splitting (V6) — adds transaction_participants (titularity/split, separate from
-- created_by authorship) and financial_transactions.split_mode. Backfills one 100% participation
-- per existing transaction so every row keeps SUM(share_amount) == amount. Pure SQL only.
--

ALTER TABLE public.financial_transactions
    ADD COLUMN split_mode character varying(16) NOT NULL DEFAULT 'EQUAL';


--
-- Name: transaction_participants; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.transaction_participants (
    id bigint NOT NULL,
    transaction_id bigint NOT NULL,
    member_user_id bigint NOT NULL,
    share_amount numeric(38,2) NOT NULL
);


ALTER TABLE public.transaction_participants ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.transaction_participants_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


ALTER TABLE ONLY public.transaction_participants
    ADD CONSTRAINT transaction_participants_pkey PRIMARY KEY (id);


ALTER TABLE ONLY public.transaction_participants
    ADD CONSTRAINT uk_txn_participants_txn_member UNIQUE (transaction_id, member_user_id);


ALTER TABLE ONLY public.transaction_participants
    ADD CONSTRAINT fk_txn_participants_transaction FOREIGN KEY (transaction_id) REFERENCES public.financial_transactions(id) ON DELETE CASCADE;


ALTER TABLE ONLY public.transaction_participants
    ADD CONSTRAINT fk_txn_participants_member FOREIGN KEY (member_user_id) REFERENCES public.users(id);


CREATE INDEX idx_txn_participants_txn ON public.transaction_participants USING btree (transaction_id);
CREATE INDEX idx_txn_participants_member ON public.transaction_participants USING btree (member_user_id);


-- Backfill: every existing transaction becomes a single 100% participation for its author.
INSERT INTO public.transaction_participants (transaction_id, member_user_id, share_amount)
SELECT id, created_by, amount FROM public.financial_transactions;
