--
-- Transaction Line Items (V7) — adds transaction_items, an additive child of financial_transactions
-- letting a transaction be broken into 0..N items, each with its own description, amount, quantity,
-- and optional category. No backfill: zero items = today's behavior. Pure SQL only.
--

--
-- Name: transaction_items; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.transaction_items (
    id bigint NOT NULL,
    transaction_id bigint NOT NULL,
    category_id bigint,
    description character varying(255) NOT NULL,
    amount numeric(19,2) NOT NULL,
    quantity integer NOT NULL DEFAULT 1,
    CONSTRAINT transaction_items_amount_check CHECK ((amount > (0)::numeric)),
    CONSTRAINT transaction_items_quantity_check CHECK ((quantity > 0))
);


ALTER TABLE public.transaction_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.transaction_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


ALTER TABLE ONLY public.transaction_items
    ADD CONSTRAINT transaction_items_pkey PRIMARY KEY (id);


ALTER TABLE ONLY public.transaction_items
    ADD CONSTRAINT fk_txn_items_transaction FOREIGN KEY (transaction_id) REFERENCES public.financial_transactions(id) ON DELETE CASCADE;


ALTER TABLE ONLY public.transaction_items
    ADD CONSTRAINT fk_txn_items_category FOREIGN KEY (category_id) REFERENCES public.financial_transaction_categories(id);


CREATE INDEX idx_txn_items_txn ON public.transaction_items USING btree (transaction_id);
CREATE INDEX idx_txn_items_category ON public.transaction_items USING btree (category_id);
