--
-- Recurring/Installment Series Editing (V8) — introduces recurrence_definitions, the
-- schedule-defining "parent" of a series of financial_transactions occurrences, and
-- recurrence_definition_participants, its split-of-record. Adds a nullable
-- financial_transactions.recurrence_definition_id FK linking each occurrence back to its
-- definition. Backfill is metadata-only: it derives one definition per distinct existing
-- series_id from that series' EARLIEST occurrence and links occurrences to it — it never
-- rewrites any occurrence's amount, description, category_id, or participant rows.
-- Pure SQL only.
--

--
-- Name: recurrence_definitions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.recurrence_definitions (
    id bigint NOT NULL,
    plan_id bigint NOT NULL,
    created_by bigint NOT NULL,
    category_id bigint,
    series_id character varying(255) NOT NULL,
    type character varying(16) NOT NULL,
    amount numeric(38,2) NOT NULL,
    description character varying(255) NOT NULL,
    mode character varying(16) NOT NULL,
    recurrence_interval character varying(16),
    parcels_number integer,
    first_parcel integer,
    start_date date NOT NULL,
    end_date date,
    split_mode character varying(16) NOT NULL DEFAULT 'EQUAL',
    generated_through date
);


ALTER TABLE public.recurrence_definitions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.recurrence_definitions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


ALTER TABLE ONLY public.recurrence_definitions
    ADD CONSTRAINT recurrence_definitions_pkey PRIMARY KEY (id);


ALTER TABLE ONLY public.recurrence_definitions
    ADD CONSTRAINT uk_recurrence_definitions_series_id UNIQUE (series_id);


ALTER TABLE ONLY public.recurrence_definitions
    ADD CONSTRAINT fk_recdef_plan FOREIGN KEY (plan_id) REFERENCES public.plans(id);


ALTER TABLE ONLY public.recurrence_definitions
    ADD CONSTRAINT fk_recdef_created_by FOREIGN KEY (created_by) REFERENCES public.users(id);


ALTER TABLE ONLY public.recurrence_definitions
    ADD CONSTRAINT fk_recdef_category FOREIGN KEY (category_id) REFERENCES public.financial_transaction_categories(id);


CREATE INDEX idx_recdef_plan_id ON public.recurrence_definitions USING btree (plan_id);
CREATE INDEX idx_recdef_series_id ON public.recurrence_definitions USING btree (series_id);


--
-- Name: recurrence_definition_participants; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.recurrence_definition_participants (
    id bigint NOT NULL,
    recurrence_definition_id bigint NOT NULL,
    member_user_id bigint NOT NULL,
    share_amount numeric(38,2) NOT NULL
);


ALTER TABLE public.recurrence_definition_participants ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.recurrence_definition_participants_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


ALTER TABLE ONLY public.recurrence_definition_participants
    ADD CONSTRAINT recurrence_definition_participants_pkey PRIMARY KEY (id);


ALTER TABLE ONLY public.recurrence_definition_participants
    ADD CONSTRAINT uk_recdef_participants_def_member UNIQUE (recurrence_definition_id, member_user_id);


ALTER TABLE ONLY public.recurrence_definition_participants
    ADD CONSTRAINT fk_recdef_participants_definition FOREIGN KEY (recurrence_definition_id) REFERENCES public.recurrence_definitions(id) ON DELETE CASCADE;


ALTER TABLE ONLY public.recurrence_definition_participants
    ADD CONSTRAINT fk_recdef_participants_member FOREIGN KEY (member_user_id) REFERENCES public.users(id);


CREATE INDEX idx_recdef_participants_definition ON public.recurrence_definition_participants USING btree (recurrence_definition_id);
CREATE INDEX idx_recdef_participants_member ON public.recurrence_definition_participants USING btree (member_user_id);


--
-- financial_transactions: add nullable recurrence_definition_id FK column
--

ALTER TABLE public.financial_transactions
    ADD COLUMN recurrence_definition_id bigint;

ALTER TABLE ONLY public.financial_transactions
    ADD CONSTRAINT fk_ft_recurrence_definition FOREIGN KEY (recurrence_definition_id) REFERENCES public.recurrence_definitions(id);

CREATE INDEX idx_ft_recurrence_definition_id ON public.financial_transactions USING btree (recurrence_definition_id);


--
-- Backfill (metadata-only): one recurrence_definitions row per distinct existing series_id,
-- derived from that series' earliest occurrence. Never touches amount/description/category_id/
-- participants of any occurrence — only populates the new parent row and the new FK column.
--

WITH series_bounds AS (
    SELECT series_id, MIN(start_date) AS min_date, MAX(start_date) AS max_date
    FROM public.financial_transactions
    WHERE series_id IS NOT NULL
    GROUP BY series_id
),
earliest AS (
    SELECT DISTINCT ON (series_id) *
    FROM public.financial_transactions
    WHERE series_id IS NOT NULL
    ORDER BY series_id, start_date
)
INSERT INTO public.recurrence_definitions (
    plan_id, created_by, category_id, series_id, type, amount, description,
    mode, recurrence_interval, parcels_number, first_parcel, start_date, end_date, split_mode
)
SELECT
    e.plan_id,
    e.created_by,
    e.category_id,
    e.series_id,
    e.type,
    e.amount,
    regexp_replace(e.description, '\s*\(\d+/\d+\)\s*$', ''),
    CASE WHEN e.parcels_number IS NOT NULL THEN 'INSTALLMENT' ELSE 'RECURRING' END,
    'MONTHLY',
    e.parcels_number,
    CASE WHEN e.parcels_number IS NOT NULL
         THEN COALESCE(substring(e.description from '\((\d+)/\d+\)')::int, 1)
         ELSE NULL
    END,
    e.start_date,
    CASE WHEN e.parcels_number IS NOT NULL THEN NULL ELSE sb.max_date END,
    e.split_mode
FROM earliest e
JOIN series_bounds sb ON sb.series_id = e.series_id;


-- Link every occurrence of a series back to its new recurrence_definitions parent.
UPDATE public.financial_transactions ft
    SET recurrence_definition_id = rd.id
    FROM public.recurrence_definitions rd
    WHERE ft.series_id = rd.series_id;


-- Seed each definition's participant split from its earliest occurrence's own participants.
WITH earliest AS (
    SELECT DISTINCT ON (series_id) id, series_id
    FROM public.financial_transactions
    WHERE series_id IS NOT NULL
    ORDER BY series_id, start_date
)
INSERT INTO public.recurrence_definition_participants (recurrence_definition_id, member_user_id, share_amount)
SELECT rd.id, tp.member_user_id, tp.share_amount
FROM public.recurrence_definitions rd
JOIN earliest e ON e.series_id = rd.series_id
JOIN public.transaction_participants tp ON tp.transaction_id = e.id;
